const lessonData = {
    "01_AlijaIzetbegovic.mp3": [{
        text: `Alija Izetbegović was a lawyer and philosopher who became the first President of Bosnia and Herzegovina. He spent many years in prison because the Communist government did not like his religious and political ideas. When Yugoslavia began to break apart, he led his people toward independence. During the Bosnian War, he stayed in the capital city of Sarajevo while it was under attack. He worked hard to protect the unity of his country and to save his people from destruction. In 1995, he signed the Dayton Peace Agreement to end the fighting. He is known as the father of the Bosnian nation because he helped the country survive its most difficult time. He is respected for his wisdom and his dedication to freedom and justice.`,
        dict: { "lawyer": "avukat", "philosopher": "filozof", "President": "başkan", "years": "yıllar", "prison": "hapishane", "government": "hükümet", "ideas": "fikirler", "people": "insanlar", "independence": "bağımsızlık", "War": "savaş", "capital": "başkent", "city": "şehir", "attack": "saldırı", "unity": "birlik", "country": "ülke", "destruction": "yıkım", "Agreement": "anlaşma", "fighting": "çatışma/savaşma", "father": "baba", "nation": "ulus/millet", "time": "zaman", "wisdom": "bilgelik", "dedication": "adanmışlık", "freedom": "özgürlük", "justice": "adalet", "became": "oldu", "spent": "geçirdi", "did not like": "sevmedi", "began": "başladı", "break apart": "parçalanmak", "led": "yönetti/önderlik etti", "stayed": "kaldı", "worked": "çalıştı", "protect": "korumak", "save": "kurtarmak", "signed": "imzaladı", "end": "bitirmek", "known": "bilinir", "helped": "yardım etti", "survive": "hayatta kalmak", "respected": "saygı duyulan", "first": "ilk", "many": "birçok", "Communist": "komünist", "religious": "dini", "political": "siyasi", "hard": "sıkı", "most": "en", "difficult": "zor", "because": "çünkü", "toward": "doğru", "During": "sırasında", "while": "iken", "under": "altında" },
        questions: [ {q:"Was he a lawyer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he spend years in prison?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he in Sarajevo during the war?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sign a peace agreement?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he known as the father of the nation?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he survive a difficult time?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he respected for his wisdom?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "02_AmilcarCabral.mp3": [{
        text: `Amílcar Cabral was a brilliant engineer and a revolutionary leader in West Africa. He fought against Portuguese colonial rule in Guinea-Bissau and Cape Verde. Cabral believed that freedom was not just about removing foreign soldiers, but also about improving the lives of the poor through education and farming. He organized a very successful guerrilla war that forced the Portuguese army to retreat. He was a great thinker whose books about culture and independence are still studied today. Tragically, he was killed by a rival group just months before his country became free. Even though he did not see the independence he fought for, he is remembered as one of Africa’s greatest heroes.`,
        dict: { "engineer": "mühendis", "leader": "lider", "Africa": "Afrika", "rule": "yönetim", "freedom": "özgürlük", "soldiers": "askerler", "lives": "hayatlar", "education": "eğitim", "farming": "çiftçilik", "war": "savaş", "army": "ordu", "thinker": "düşünür", "books": "kitaplar", "culture": "kültür", "independence": "bağımsızlık", "group": "grup", "months": "aylar", "country": "ülke", "heroes": "kahramanlar", "fought": "savaştı", "believed": "inandı", "removing": "kaldırmak/uzaklaştırmak", "improving": "geliştirmek/iyileştirmek", "organized": "organize etti", "forced": "zorladı", "retreat": "geri çekilmek", "studied": "incelenir/okunur", "killed": "öldürüldü", "became": "oldu", "did not see": "görmedi", "remembered": "hatırlanır", "brilliant": "parlak/zeki", "revolutionary": "devrimci", "West": "Batı", "Portuguese": "Portekiz", "colonial": "sömürge", "foreign": "yabancı", "poor": "fakir/yoksul", "very": "çok", "successful": "başarılı", "guerrilla": "gerilla", "great": "büyük/harika", "rival": "rakip", "free": "özgür", "greatest": "en büyük", "against": "karşı", "just": "sadece", "about": "hakkında", "also": "ayrıca", "through": "yoluyla", "still": "hala", "today": "bugün", "Tragically": "trajik bir şekilde", "before": "önce", "Even though": "olmasına rağmen" },
        questions: [ {q:"Was Cabral an engineer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he fight against French rule?", a_en:"No", a_tr:"Hayır"}, {q:"Did he believe in education?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he organize a guerrilla war?", a_en:"Yes", a_tr:"Evet"}, {q:"Are his books still studied?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he killed before his country became free?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he remembered as a hero?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "03_AngelaDavis.mp3": [{
        text: `Angela Davis is a famous activist and teacher in the United States. She became a leader in the civil rights movement during the 1960s. She spoke out strongly against racism and the unfair treatment of prisoners. In 1970, she became one of the most famous women in the world when she was placed on the FBI's Most Wanted List. She spent over a year in jail for a crime she did not commit. After a long trial, she was found not guilty. Today, she continues to fight for the rights of all people. She believes that we must change the prison system and work for true equality. She is a powerful symbol of resistance and courage for people around the world.`,
        dict: { "activist": "aktivist", "teacher": "öğretmen", "States": "Devletler", "leader": "lider", "rights": "haklar", "movement": "hareket", "racism": "ırkçılık", "treatment": "muamele", "prisoners": "mahkumlar", "women": "kadınlar", "world": "dünya", "List": "liste", "year": "yıl", "jail": "hapishane", "crime": "suç", "trial": "dava/yargılanma", "Today": "bugün", "people": "insanlar", "prison": "hapishane", "system": "sistem", "work": "çalışma", "equality": "eşitlik", "symbol": "sembol", "resistance": "direniş", "courage": "cesaret", "became": "oldu", "spoke out": "açıkça konuştu", "placed": "yerleştirildi", "spent": "geçirdi", "commit": "işlemek", "found": "bulundu", "continues": "devam ediyor", "fight": "savaşmak", "believes": "inanıyor", "must change": "değiştirmeliyiz", "famous": "ünlü", "civil": "sivil", "unfair": "adil olmayan", "most": "en", "Wanted": "aranan", "long": "uzun", "guilty": "suçlu", "all": "tüm", "true": "gerçek", "powerful": "güçlü", "during": "sırasında", "strongly": "güçlü bir şekilde", "against": "karşı", "when": "zaman/olduğunda", "over": "üzerinde/fazla", "After": "sonra", "around": "etrafında" },
        questions: [ {q:"Is Angela Davis a teacher?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she speak out against racism?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she on the FBI Most Wanted List?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she commit the crime?", a_en:"No", a_tr:"Hayır"}, {q:"Did she spend time in jail?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she found not guilty?", a_en:"Yes", a_tr:"Evet"}, {q:"Does she fight for the rights of all people?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "04_AssataShakur.mp3": [{
        text: `Assata Shakur was an activist in the Black Panther Party who fought for the rights of Black Americans. In 1973, she was involved in a gunfight on a highway where a police officer was killed. She was injured and captured by the police. Even though she said she was innocent, she was sent to prison for life. In 1979, she managed to escape from prison with the help of her friends. She traveled secretly to Cuba, where the government gave her protection. She still lives in Cuba today. Many activists see her as a hero who survived a very unfair system, while the US government still wants to arrest her. Her story is a famous example of the struggle for civil rights.`,
        dict: { "activist": "aktivist", "Party": "parti", "rights": "haklar", "Americans": "Amerikalılar", "gunfight": "silahlı çatışma", "highway": "otoyol", "police": "polis", "officer": "memur", "life": "hayat/ömür boyu", "prison": "hapishane", "help": "yardım", "friends": "arkadaşlar", "Cuba": "Küba", "government": "hükümet", "protection": "koruma", "activists": "aktivistler", "hero": "kahraman", "system": "sistem", "story": "hikaye", "example": "örnek", "struggle": "mücadele", "fought": "savaştı", "involved": "karıştı/dahil oldu", "killed": "öldürüldü", "injured": "yaralandı", "captured": "yakalandı", "said": "dedi", "sent": "gönderildi", "managed": "başardı", "escape": "kaçmak", "traveled": "seyahat etti", "gave": "verdi", "lives": "yaşar", "see": "görür", "survived": "hayatta kaldı", "wants": "istiyor", "arrest": "tutuklamak", "Black": "siyah", "innocent": "masum", "Many": "birçok", "very": "çok", "unfair": "adil olmayan", "famous": "ünlü", "civil": "sivil", "where": "nerede/ki orada", "Even though": "olmasına rağmen", "secretly": "gizlice", "still": "hala", "today": "bugün", "while": "iken" },
        questions: [ {q:"Was she in the Black Panther Party?", a_en:"Yes", a_tr:"Evet"}, {q:"Was a police officer killed?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she captured by the police?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she sent to prison for life?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she escape from prison?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she travel to Cuba?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the US government want to arrest her?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "05_BhagatSingh.mp3": [{
        text: `Bhagat Singh was a young and brave revolutionary in India. He fought against British rule because he wanted his country to be free and fair for everyone. He did not agree with non-violent protests only; he believed that strong action was needed to wake up the people. In 1929, he threw a small bomb into a government building to protest against unfair laws. He did not want to hurt anyone, but he wanted the British to listen. He was arrested and stayed very strong while in prison. The British executed him when he was only 23 years old. His sacrifice made him a legend in India and Pakistan. Today, young people still look to him as a symbol of bravery and patriotism.`,
        dict: { "revolutionary": "devrimci", "India": "Hindistan", "rule": "yönetim", "country": "ülke", "everyone": "herkes", "protests": "protestolar", "action": "eylem", "people": "insanlar", "bomb": "bomba", "government": "hükümet", "building": "bina", "laws": "yasalar", "anyone": "hiç kimse", "prison": "hapishane", "years": "yıllar", "sacrifice": "fedakarlık", "legend": "efsane", "Pakistan": "Pakistan", "Today": "bugün", "symbol": "sembol", "bravery": "cesaret", "patriotism": "vatanseverlik", "fought": "savaştı", "wanted": "istedi", "be": "olmak", "agree": "katılmak/aynı fikirde olmak", "believed": "inandı", "needed": "gerekli", "wake up": "uyandırmak", "threw": "attı", "protest": "protesto etmek", "hurt": "incitmek", "listen": "dinlemek", "arrested": "tutuklandı", "stayed": "kaldı", "executed": "idam edildi", "made": "yaptı", "look": "bakar", "young": "genç", "brave": "cesur", "British": "İngiliz", "free": "özgür", "fair": "adil", "non-violent": "şiddetsiz", "only": "sadece", "strong": "güçlü", "small": "küçük", "unfair": "adil olmayan", "very": "çok", "against": "karşı", "because": "çünkü", "into": "içine", "while": "iken", "when": "zaman/olduğunda", "still": "hala" },
        questions: [ {q:"Was Bhagat Singh from India?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he agree with non-violent protests only?", a_en:"No", a_tr:"Hayır"}, {q:"Did he throw a small bomb?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to hurt anyone?", a_en:"No", a_tr:"Hayır"}, {q:"Was he arrested?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he executed?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a symbol of bravery?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "06_BobbySands.mp3": [{
        text: `Bobby Sands was a member of the IRA in Northern Ireland. He wanted his country to be independent of British rule. While he was in prison, he led a famous hunger strike in 1981. He and other prisoners refused to eat because they wanted to be treated as political prisoners, not as criminals. During the strike, the people actually elected him to the British Parliament. After 66 days without food, Bobby Sands died. His death caused a massive reaction around the world and brought a lot of attention to the problems in Northern Ireland. He is remembered as a man who was willing to give his life for his political beliefs and his country’s freedom.`,
        dict: { "member": "üye", "Ireland": "İrlanda", "country": "ülke", "rule": "yönetim", "prison": "hapishane", "hunger": "açlık", "strike": "grev", "prisoners": "mahkumlar", "criminals": "suçlular", "people": "insanlar", "Parliament": "Parlamento", "days": "günler", "food": "yiyecek", "death": "ölüm", "reaction": "tepki", "world": "dünya", "attention": "dikkat", "problems": "sorunlar", "man": "adam", "life": "hayat", "beliefs": "inançlar", "freedom": "özgürlük", "wanted": "istedi", "be": "olmak", "led": "yönetti/önderlik etti", "refused": "reddetti", "eat": "yemek", "treated": "muamele görmek", "elected": "seçti", "died": "öldü", "caused": "sebep oldu", "brought": "getirdi", "remembered": "hatırlanır", "give": "vermek", "Northern": "Kuzey", "independent": "bağımsız", "British": "İngiliz", "famous": "ünlü", "other": "diğer", "political": "siyasi", "massive": "muazzam", "willing": "istekli", "While": "iken", "because": "çünkü", "not": "değil", "During": "sırasında", "actually": "aslında", "After": "sonra", "without": "olmaksızın", "around": "etrafında", "lot of": "çok" },
        questions: [ {q:"Was Bobby Sands in Northern Ireland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead a hunger strike?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse to eat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people elect him to Parliament?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die after 66 days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his death cause a massive reaction?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give his life for freedom?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "07_CheGuevara.mp3": [{
        text: `Ernesto "Che" Guevara was a doctor from Argentina who became a global symbol of revolution. While traveling as a young man, he saw the terrible poverty in Latin America and decided to fight for the poor. He joined Fidel Castro and helped lead the Cuban Revolution to victory in 1959. After the war, he held important jobs in the new government, but he wanted to help other countries too. He traveled to Africa and then to Bolivia to start new revolutions. He was captured and killed in the mountains of Bolivia in 1967. Today, his face is famous all over the world. People see him as a symbol of rebellion against unfair power.`,
        dict: { "doctor": "doktor", "Argentina": "Arjantin", "symbol": "sembol", "revolution": "devrim", "man": "adam", "poverty": "yoksulluk", "America": "Amerika", "victory": "zafer", "war": "savaş", "jobs": "işler", "government": "hükümet", "countries": "ülkeler", "revolutions": "devrimler", "mountains": "dağlar", "Today": "bugün", "face": "yüz", "world": "dünya", "People": "insanlar", "rebellion": "isyan", "power": "güç", "became": "oldu", "traveling": "seyahat eden", "saw": "gördü", "decided": "karar verdi", "fight": "savaşmak", "joined": "katıldı", "helped": "yardım etti", "lead": "yönetmek/önderlik etmek", "held": "tuttu/aldı", "wanted": "istedi", "help": "yardım etmek", "traveled": "seyahat etti", "start": "başlamak", "captured": "yakalandı", "killed": "öldürüldü", "see": "görür", "global": "küresel", "young": "genç", "terrible": "korkunç", "poor": "fakir/yoksul", "Cuban": "Kübalı", "important": "önemli", "new": "yeni", "other": "diğer", "famous": "ünlü", "unfair": "adil olmayan", "While": "iken", "After": "sonra", "too": "de/da", "then": "sonra", "all over": "her yerinde", "against": "karşı" },
        questions: [ {q:"Was Che Guevara a doctor?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he from Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he fight for the poor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help lead the Cuban Revolution?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he travel to Africa and Bolivia?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he captured in Bolivia?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his face famous all over the world?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "08_DenizGezmis.mp3": [{
        text: `Deniz Gezmiş was a student leader and a revolutionary in Turkey. During the late 1960s, he led many protests against foreign influence and for the rights of workers and students. He believed that Turkey should be a completely independent and socialist country. He founded a group that used armed action to fight the government. After a military coup in 1971, he was caught and put on trial. He remained very brave and never apologized for his actions. He was executed by hanging in 1972 at the age of 25. His death made him a hero for many young people in Turkey. He is still remembered today as a symbol of the fight for a better and fairer world.`,
        dict: { "student": "öğrenci", "leader": "lider", "revolutionary": "devrimci", "Turkey": "Türkiye", "protests": "protestolar", "influence": "etki", "rights": "haklar", "workers": "işçiler", "students": "öğrenciler", "country": "ülke", "group": "grup", "action": "eylem", "government": "hükümet", "coup": "darbe", "trial": "dava", "actions": "eylemler", "hanging": "asma", "age": "yaş", "death": "ölüm", "hero": "kahraman", "people": "insanlar", "symbol": "sembol", "fight": "savaş/mücadele", "world": "dünya", "led": "yönetti", "believed": "inandı", "should be": "olmalı", "founded": "kurdu", "used": "kullandı", "caught": "yakalandı", "put": "konuldu", "remained": "kaldı", "apologized": "özür diledi", "executed": "idam edildi", "made": "yaptı", "remembered": "hatırlanır", "late": "geç/sonları", "many": "birçok", "foreign": "yabancı", "completely": "tamamen", "independent": "bağımsız", "socialist": "sosyalist", "armed": "silahlı", "military": "askeri", "very": "çok", "brave": "cesur", "young": "genç", "better": "daha iyi", "fairer": "daha adil", "During": "sırasında", "against": "karşı", "After": "sonra", "never": "asla", "still": "hala", "today": "bugün" },
        questions: [ {q:"Was Deniz Gezmiş a student leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead protests?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want a completely independent country?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he caught after a military coup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he apologize for his actions?", a_en:"No", a_tr:"Hayır"}, {q:"Was he executed by hanging?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he remembered as a hero?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "09_DjamilaBouhired.mp3": [{
        text: `Djamila Bouhired is one of the most famous women in the history of North Africa. She was a resistance fighter who fought for Algeria's independence from France. During the war, she carried out dangerous missions in the city of Algiers. She was eventually captured and tortured by French soldiers, but she never gave away the secrets of her group. She was sentenced to death, but people all over the world protested to save her life. Because of this international pressure, she was released when Algeria became free in 1962. She is a national hero and a symbol of how women played a vital role in the struggle for freedom and national dignity.`,
        dict: { "women": "kadınlar", "history": "tarih", "Africa": "Afrika", "resistance": "direniş", "fighter": "savaşçı", "independence": "bağımsızlık", "France": "Fransa", "war": "savaş", "missions": "görevler", "city": "şehir", "soldiers": "askerler", "secrets": "sırlar", "group": "grup", "death": "ölüm", "people": "insanlar", "world": "dünya", "life": "hayat", "pressure": "baskı", "hero": "kahraman", "symbol": "sembol", "role": "rol", "struggle": "mücadele", "freedom": "özgürlük", "dignity": "onur", "fought": "savaştı", "carried out": "gerçekleştirdi", "captured": "yakalandı", "tortured": "işkence gördü", "gave away": "ele verdi", "sentenced": "mahkum edildi", "protested": "protesto etti", "save": "kurtarmak", "released": "serbest bırakıldı", "became": "oldu", "played": "oynadı", "famous": "ünlü", "North": "Kuzey", "dangerous": "tehlikeli", "French": "Fransız", "international": "uluslararası", "free": "özgür", "national": "ulusal", "vital": "hayati", "most": "en", "During": "sırasında", "eventually": "sonunda", "never": "asla", "all over": "her yerinde", "Because of": "yüzünden", "when": "zaman/olduğunda", "how": "nasıl" },
        questions: [ {q:"Was Djamila a resistance fighter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she fight for Algeria's independence?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she carry out dangerous missions?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she tortured by French soldiers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she give away her group's secrets?", a_en:"No", a_tr:"Hayır"}, {q:"Was she released in 1962?", a_en:"Yes", a_tr:"Evet"}, {q:"Is she a national hero?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "10_FrantzFanon.mp3": [{
        text: `Frantz Fanon was a doctor and a very important writer from Martinique. He studied how colonialism and racism hurt the minds of people. He moved to Algeria and joined the fight for independence against France. He wrote several famous books, like The Wretched of the Earth, which explained why people have a right to fight for their freedom. He believed that colonized people must stand up and be proud of their own culture to be truly free. His ideas inspired many freedom movements in Africa, the Caribbean, and America. Although he died very young from a sickness, his books are still read by millions of people who want to understand justice and equality.`,
        dict: { "doctor": "doktor", "writer": "yazar", "colonialism": "sömürgecilik", "racism": "ırkçılık", "minds": "zihinler", "people": "insanlar", "fight": "savaş", "independence": "bağımsızlık", "France": "Fransa", "books": "kitaplar", "Earth": "Dünya", "right": "hak", "freedom": "özgürlük", "culture": "kültür", "ideas": "fikirler", "movements": "hareketler", "Africa": "Afrika", "America": "Amerika", "sickness": "hastalık", "millions": "milyonlarca", "justice": "adalet", "equality": "eşitlik", "studied": "inceledi", "hurt": "incitti/zarar verdi", "moved": "taşındı", "joined": "katıldı", "wrote": "yazdı", "explained": "açıkladı", "have": "sahip olmak", "believed": "inandı", "must": "zorunda olmak", "stand up": "ayağa kalkmak", "be": "olmak", "inspired": "ilham verdi", "died": "öldü", "read": "okunur", "want": "istemek", "understand": "anlamak", "important": "önemli", "several": "birkaç", "famous": "ünlü", "Wretched": "sefiller", "colonized": "sömürgeleştirilmiş", "proud": "gururlu", "own": "kendi", "truly": "gerçekten", "free": "özgür", "many": "birçok", "young": "genç", "very": "çok", "how": "nasıl", "against": "karşı", "like": "gibi", "why": "neden", "Although": "rağmen", "still": "hala" },
        questions: [ {q:"Was Frantz Fanon a writer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he study racism?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Algeria?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he write famous books?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he believe colonized people must stand up?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die very young?", a_en:"Yes", a_tr:"Evet"}, {q:"Are his books still read today?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "11_FredHampton.mp3": [{
        text: `Fred Hampton was a brilliant young leader in the Black Panther Party in Chicago. He was a very talented speaker who wanted to bring people of all races together to fight against poverty and racism. He created the "Rainbow Coalition" to unite Black, Hispanic, and white working-class people. He also started programs to give free breakfast to children in poor neighborhoods. The government and the police were very afraid of his power to unite people. In 1969, while he was sleeping in his apartment, the police and the FBI raided the building and killed him. He was only 21 years old. His death is seen as a tragic assassination of a man who wanted peace and unity for everyone.`,
        dict: { "leader": "lider", "Party": "parti", "speaker": "konuşmacı", "people": "insanlar", "races": "ırklar", "poverty": "yoksulluk", "racism": "ırkçılık", "Coalition": "koalisyon", "working-class": "işçi sınıfı", "programs": "programlar", "breakfast": "kahvaltı", "children": "çocuklar", "neighborhoods": "mahalleler", "government": "hükümet", "police": "polis", "power": "güç", "apartment": "daire", "building": "bina", "death": "ölüm", "assassination": "suikast", "man": "adam", "peace": "barış", "unity": "birlik", "everyone": "herkes", "wanted": "istedi", "bring": "getirmek", "fight": "savaşmak", "created": "yarattı", "unite": "birleştirmek", "started": "başlattı", "give": "vermek", "sleeping": "uyuyan", "raided": "baskın yaptı", "killed": "öldürdü", "seen": "görülür", "brilliant": "parlak/zeki", "young": "genç", "Black": "siyah", "talented": "yetenekli", "all": "tüm", "Hispanic": "Hispanik", "white": "beyaz", "free": "ücretsiz/bedava", "poor": "fakir", "afraid": "korkmuş", "tragic": "trajik", "very": "çok", "together": "birlikte", "against": "karşı", "also": "ayrıca", "while": "iken", "only": "sadece" },
        questions: [ {q:"Was Fred Hampton a talented speaker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he create the Rainbow Coalition?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give free breakfast to children?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the police afraid of him?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he sleeping when the police raided his apartment?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he only 21 years old?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want peace and unity?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "12_HoChiMinh.mp3": [{
        text: `Ho Chi Minh was the most important leader in the history of Vietnam. He spent many years traveling the world to find a way to make his country free from French rule. He founded the Communist Party of Vietnam and led the resistance for decades. After the French left, he led North Vietnam during the war against the United States. He was a very simple man who lived a quiet life, but his people loved him and called him "Uncle Ho." He died before the war ended, but his dream of a united and independent Vietnam finally came true in 1975. The largest city in the country was renamed Ho Chi Minh City to honor his memory.`,
        dict: { "leader": "lider", "history": "tarih", "years": "yıllar", "world": "dünya", "way": "yol/yöntem", "country": "ülke", "rule": "yönetim", "Party": "parti", "resistance": "direniş", "decades": "on yıllar", "war": "savaş", "States": "Devletler", "man": "adam", "life": "hayat", "people": "insanlar", "Uncle": "amca", "dream": "rüya", "city": "şehir", "memory": "anı/hatıra", "spent": "geçirdi", "traveling": "seyahat eden", "find": "bulmak", "make": "yapmak", "founded": "kurdu", "led": "yönetti", "left": "ayrıldı", "lived": "yaşadı", "loved": "sevdi", "called": "adlandırdı", "died": "öldü", "ended": "bitti", "came true": "gerçekleşti", "renamed": "yeniden adlandırıldı", "honor": "onurlandırmak", "important": "önemli", "many": "birçok", "free": "özgür", "French": "Fransız", "Communist": "komünist", "North": "Kuzey", "simple": "basit", "quiet": "sessiz", "united": "birleşik", "independent": "bağımsız", "largest": "en büyük", "most": "en", "After": "sonra", "during": "sırasında", "against": "karşı", "very": "çok", "before": "önce", "finally": "sonunda" },
        questions: [ {q:"Was Ho Chi Minh from Vietnam?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he spend years traveling the world?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead the resistance?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his people call him Uncle Ho?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live a simple life?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die before the war ended?", a_en:"Yes", a_tr:"Evet"}, {q:"Was a city renamed to honor him?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "13_MalcolmX.mp3": [{
        text: `Malcolm X was a powerful leader who fought for the rights of African Americans. He believed that Black people should be proud of their identity and defend themselves against unfair treatment. He was a very famous speaker who told the truth about racism in America. Later in his life, he went on a religious trip to Mecca. This experience changed his mind about many things, and he began to believe that people of all races could work together for human rights. He was a man of great courage who was never afraid to say what he thought. He was killed in 1965, but his ideas about justice and self-respect continue to inspire millions of people around the world.`,
        dict: { "leader": "lider", "rights": "haklar", "Americans": "Amerikalılar", "people": "insanlar", "identity": "kimlik", "treatment": "muamele", "speaker": "konuşmacı", "truth": "gerçek", "racism": "ırkçılık", "life": "hayat", "trip": "yolculuk", "experience": "deneyim", "mind": "akıl/fikir", "things": "şeyler", "races": "ırklar", "man": "adam", "courage": "cesaret", "ideas": "fikirler", "justice": "adalet", "self-respect": "özsaygı", "millions": "milyonlarca", "world": "dünya", "fought": "savaştı", "believed": "inandı", "should be": "olmalı", "defend": "savunmak", "told": "söyledi", "went": "gitti", "changed": "değiştirdi", "began": "başladı", "work": "çalışmak", "say": "söylemek", "thought": "düşündü", "killed": "öldürüldü", "continue": "devam etmek", "inspire": "ilham vermek", "powerful": "güçlü", "African": "Afrikalı", "Black": "siyah", "proud": "gururlu", "unfair": "adil olmayan", "famous": "ünlü", "religious": "dini", "many": "birçok", "all": "tüm", "human": "insan", "great": "büyük", "afraid": "korkmuş", "against": "karşı", "about": "hakkında", "Later": "daha sonra", "together": "birlikte", "never": "asla", "what": "ne", "around": "etrafında" },
        questions: [ {q:"Was Malcolm X a powerful leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a famous speaker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell the truth about racism?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he go on a religious trip to Mecca?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his experience change his mind?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he afraid to say what he thought?", a_en:"No", a_tr:"Hayır"}, {q:"Do his ideas continue to inspire people?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "14_NelsonMandela.mp3": [{
        text: `Nelson Mandela is one of the most respected people in history. He spent his life fighting against "apartheid," which was a system of cruel racism in South Africa. He was a lawyer who became a leader of the resistance. Because of his work, the government put him in prison for 27 years. Even while he was in a small cell, he never gave up his hope for a free country. He was finally released in 1990 and worked with his former enemies to create a new democracy. In 1994, he became the first Black President of South Africa. He chose to forgive those who hurt him, and he showed the world the power of peace and reconciliation.`,
        dict: { "people": "insanlar", "history": "tarih", "life": "hayat", "system": "sistem", "racism": "ırkçılık", "Africa": "Afrika", "lawyer": "avukat", "leader": "lider", "resistance": "direniş", "work": "çalışma", "government": "hükümet", "prison": "hapishane", "years": "yıllar", "cell": "hücre", "hope": "umut", "country": "ülke", "enemies": "düşmanlar", "democracy": "demokrasi", "President": "başkan", "world": "dünya", "power": "güç", "peace": "barış", "reconciliation": "uzlaşma", "spent": "geçirdi", "fighting": "savaşan", "became": "oldu", "put": "koydu", "gave up": "vazgeçti", "released": "serbest bırakıldı", "worked": "çalıştı", "create": "yaratmak", "chose": "seçti", "forgive": "affetmek", "hurt": "inciten", "showed": "gösterdi", "respected": "saygı duyulan", "cruel": "zalim", "South": "Güney", "small": "küçük", "free": "özgür", "former": "eski", "new": "yeni", "first": "ilk", "Black": "siyah", "most": "en", "against": "karşı", "Because of": "yüzünden", "Even": "hatta", "while": "iken", "never": "asla", "finally": "sonunda" },
        questions: [ {q:"Did Mandela fight against apartheid?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he put in prison for 27 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give up hope?", a_en:"No", a_tr:"Hayır"}, {q:"Was he released in 1990?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he work with his former enemies?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become the first Black President?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he choose to forgive?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "15_OmarMukhtar.mp3": [{
        text: `Omar Mukhtar was a religious teacher who became a legendary warrior in Libya. When Italy invaded his country, he organized a group of fighters to defend the land. He was an expert in "guerrilla warfare," which means attacking quickly and then hiding in the desert. For 20 years, he fought the powerful Italian army, even though his group was much smaller. He was a man of great honor and faith. He was finally captured and executed by the Italians in 1931. Before he died, he famously said that his people would never surrender. He is known as the "Lion of the Desert" and is a hero to all Libyans and Arabs.`,
        dict: { "teacher": "öğretmen", "warrior": "savaşçı", "country": "ülke", "group": "grup", "fighters": "savaşçılar", "land": "toprak", "expert": "uzman", "warfare": "savaş", "desert": "çöl", "years": "yıllar", "army": "ordu", "man": "adam", "honor": "onur", "faith": "inanç", "Italians": "İtalyanlar", "people": "insanlar", "Lion": "aslan", "hero": "kahraman", "Libyans": "Libyalılar", "Arabs": "Araplar", "became": "oldu", "invaded": "işgal etti", "organized": "organize etti", "defend": "savunmak", "means": "anlamına gelir", "attacking": "saldırma", "hiding": "saklanma", "fought": "savaştı", "captured": "yakalandı", "executed": "idam edildi", "died": "öldü", "said": "dedi", "surrender": "teslim olmak", "known": "bilinir", "religious": "dini", "legendary": "efsanevi", "powerful": "güçlü", "Italian": "İtalyan", "smaller": "daha küçük", "great": "büyük", "all": "tüm", "When": "zaman/olduğunda", "quickly": "hızlıca", "then": "sonra", "even though": "olmasına rağmen", "much": "çok", "finally": "sonunda", "Before": "önce", "famously": "ünlü bir şekilde", "never": "asla" },
        questions: [ {q:"Was Omar Mukhtar a religious teacher?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he organize a group of fighters?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he an expert in guerrilla warfare?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he fight for 20 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Was his group smaller than the Italian army?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he captured and executed?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he known as the Lion of the Desert?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "16_PatriceLumumba.mp3": [{
        text: `Patrice Lumumba was the first Prime Minister of the independent Republic of the Congo. He was a passionate leader who wanted his country to be truly free from Belgian control. He believed that Africa’s wealth should belong to African people. After he was elected, he faced many problems from foreign countries and rebels at home. Because he was very independent and strong, powerful countries became his enemies. He was removed from power in a coup and was killed in 1961. He was only 35 years old. Today, he is seen as a symbol of the struggle for African independence and a martyr for the dream of a united and strong Africa.`,
        dict: { "Minister": "bakan", "Republic": "cumhuriyet", "leader": "lider", "country": "ülke", "control": "kontrol", "wealth": "zenginlik", "people": "insanlar", "problems": "sorunlar", "countries": "ülkeler", "rebels": "isyancılar", "home": "ev/yurt", "enemies": "düşmanlar", "power": "güç", "coup": "darbe", "years": "yıllar", "Today": "bugün", "symbol": "sembol", "struggle": "mücadele", "independence": "bağımsızlık", "martyr": "şehit", "dream": "rüya", "wanted": "istedi", "be": "olmak", "believed": "inandı", "belong": "ait olmak", "elected": "seçildi", "faced": "yüzleşti", "became": "oldu", "removed": "uzaklaştırıldı", "killed": "öldürüldü", "seen": "görülür", "first": "ilk", "Prime": "başbakan", "independent": "bağımsız", "passionate": "tutkulu", "free": "özgür", "Belgian": "Belçikalı", "African": "Afrikalı", "many": "birçok", "foreign": "yabancı", "strong": "güçlü", "powerful": "güçlü", "united": "birleşik", "truly": "gerçekten", "After": "sonra", "Because": "çünkü", "very": "çok", "only": "sadece" },
        questions: [ {q:"Was Lumumba the first Prime Minister?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want his country truly free?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he face problems from foreign countries?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he removed from power in a coup?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he killed in 1961?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he only 35 years old?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he seen as a symbol of struggle?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "17_RosaParks.mp3": [{
        text: `Rosa Parks is known as the "Mother of the Civil Rights Movement." In 1955, in Alabama, she did something very brave. She refused to give up her bus seat to a white man, even though the law said she had to. Her arrest started a massive protest where Black people refused to use the buses for over a year. This protest was led by Martin Luther King Jr. and eventually forced the government to change the unfair laws. Rosa Parks showed the world that one person can start a big change just by saying "no" to injustice. She spent the rest of her life working for peace and equality for all people.`,
        dict: { "Mother": "anne", "Rights": "haklar", "Movement": "hareket", "something": "bir şey", "bus": "otobüs", "seat": "koltuk", "man": "adam", "law": "yasa", "arrest": "tutuklama", "protest": "protesto", "people": "insanlar", "buses": "otobüsler", "year": "yıl", "government": "hükümet", "laws": "yasalar", "world": "dünya", "person": "kişi", "change": "değişim", "injustice": "adaletsizlik", "rest": "geri kalan", "life": "hayat", "peace": "barış", "equality": "eşitlik", "known": "bilinir", "did": "yaptı", "refused": "reddetti", "give up": "vazgeçmek/vermek", "said": "dedi", "had to": "zorundaydı", "started": "başlattı", "use": "kullanmak", "led": "yönetildi", "forced": "zorladı", "showed": "gösterdi", "start": "başlamak", "saying": "söyleyerek", "spent": "geçirdi", "working": "çalışma", "Civil": "sivil", "brave": "cesur", "white": "beyaz", "massive": "muazzam", "Black": "siyah", "unfair": "adil olmayan", "big": "büyük", "all": "tüm", "very": "çok", "even though": "olmasına rağmen", "where": "nerede", "over": "üzerinde", "eventually": "sonunda", "just": "sadece" },
        questions: [ {q:"Is Rosa Parks known as the Mother of the Civil Rights Movement?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she refuse to give up her seat?", a_en:"Yes", a_tr:"Evet"}, {q:"Did her arrest start a massive protest?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Black people refuse to use the buses?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the protest led by Martin Luther King Jr?", a_en:"Yes", a_tr:"Evet"}, {q:"Can one person start a big change?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she work for peace and equality?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "18_SamoraMachel.mp3": [{
        text: `Samora Machel was the leader who brought independence to Mozambique. He led a long and difficult war against the Portuguese army for many years. He was a charismatic military commander who believed in socialism and equality for everyone. When the war ended in 1975, he became the first President of the country. He worked to build new schools and hospitals for the poor and to unite different groups of people. He also helped other African countries fight for their freedom. He died in a mysterious plane crash in 1986. Many people believe his enemies caused the crash. He remains a beloved hero in Mozambique and throughout Southern Africa.`,
        dict: { "leader": "lider", "independence": "bağımsızlık", "war": "savaş", "army": "ordu", "years": "yıllar", "commander": "komutan", "socialism": "sosyalizm", "equality": "eşitlik", "everyone": "herkes", "President": "başkan", "country": "ülke", "schools": "okullar", "hospitals": "hastaneler", "groups": "gruplar", "people": "insanlar", "countries": "ülkeler", "freedom": "özgürlük", "plane": "uçak", "crash": "kaza", "enemies": "düşmanlar", "hero": "kahraman", "Africa": "Afrika", "brought": "getirdi", "led": "yönetti", "believed": "inandı", "ended": "bitti", "became": "oldu", "worked": "çalıştı", "build": "inşa etmek", "unite": "birleştirmek", "helped": "yardım etti", "fight": "savaşmak", "died": "öldü", "believe": "inanmak", "caused": "sebep oldu", "remains": "kalır/devam eder", "long": "uzun", "difficult": "zor", "Portuguese": "Portekiz", "many": "birçok", "charismatic": "karizmatik", "military": "askeri", "first": "ilk", "new": "yeni", "poor": "fakir/yoksul", "different": "farklı", "other": "diğer", "African": "Afrikalı", "mysterious": "gizemli", "beloved": "sevilen", "Southern": "Güney", "against": "karşı", "When": "zaman/olduğunda", "also": "ayrıca", "throughout": "boyunca" },
        questions: [ {q:"Did Samora Machel bring independence to Mozambique?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead a war against the Portuguese army?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he believe in socialism and equality?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he build new schools and hospitals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help other African countries?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die in a plane crash?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a beloved hero?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "19_SteveBiko.mp3": [{
        text: `Steve Biko was a brilliant young leader who fought against racism in South Africa. He started the "Black Consciousness" movement, which taught Black people to be proud of themselves and their history. He believed that the first step to freedom was for people to realize they were not inferior to anyone else. The government was very afraid of his ideas and banned him from speaking to the public. In 1977, he was arrested and beaten so badly by the police that he died. He was only 30 years old. His death made the whole world angry at the South African government. He is remembered for the famous phrase: "Black is beautiful."`,
        dict: { "leader": "lider", "racism": "ırkçılık", "Africa": "Afrika", "movement": "hareket", "people": "insanlar", "history": "tarih", "step": "adım", "freedom": "özgürlük", "anyone else": "başka kimse", "government": "hükümet", "ideas": "fikirler", "public": "halk", "police": "polis", "years": "yıllar", "death": "ölüm", "world": "dünya", "phrase": "ifade", "fought": "savaştı", "started": "başlattı", "taught": "öğretti", "be": "olmak", "believed": "inandı", "realize": "fark etmek", "were not": "değildi", "banned": "yasakladı", "speaking": "konuşma", "arrested": "tutuklandı", "beaten": "dövüldü", "died": "öldü", "made": "yaptı", "remembered": "hatırlanır", "brilliant": "parlak/zeki", "young": "genç", "South": "Güney", "Black": "siyah", "proud": "gururlu", "first": "ilk", "inferior": "aşağı/düşük", "afraid": "korkmuş", "badly": "kötü", "whole": "bütün", "angry": "öfkeli", "famous": "ünlü", "beautiful": "güzel", "against": "karşı", "very": "çok", "so": "çok", "only": "sadece" },
        questions: [ {q:"Did Steve Biko fight against racism?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he start the Black Consciousness movement?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he teach people to be proud?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the government afraid of his ideas?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he beaten by the police?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die at 30 years old?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he remembered for saying Black is beautiful?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "20_ThomasSankara.mp3": [{
        text: `Thomas Sankara was the President of Burkina Faso in the 1980s. He was a very different kind of leader because he lived a very simple life and refused to be rich while his people were poor. He changed the name of his country to Burkina Faso, which means "Land of Incorruptible People." He built many schools, planted millions of trees, and was a strong supporter of women's rights. He wanted his country to be independent and not rely on money from other nations. He was killed in a coup in 1987 by people who did not like his radical changes. He is often called the "African Che Guevara" and is a hero to many young Africans today.`,
        dict: { "President": "başkan", "kind": "tür", "leader": "lider", "life": "hayat", "people": "insanlar", "name": "isim", "country": "ülke", "Land": "toprak/ülke", "schools": "okullar", "trees": "ağaçlar", "supporter": "destekçi", "rights": "haklar", "money": "para", "nations": "uluslar", "coup": "darbe", "changes": "değişiklikler", "hero": "kahraman", "Africans": "Afrikalılar", "today": "bugün", "lived": "yaşadı", "refused": "reddetti", "be": "olmak", "changed": "değiştirdi", "means": "anlamına gelir", "built": "inşa etti", "planted": "dikti", "wanted": "istedi", "rely": "güvenmek/bel bağlamak", "killed": "öldürüldü", "did not like": "sevmedi", "called": "adlandırılır", "different": "farklı", "simple": "basit", "rich": "zengin", "poor": "fakir/yoksul", "Incorruptible": "yozlaşmaz/dürüst", "many": "birçok", "millions": "milyonlarca", "strong": "güçlü", "women's": "kadınların", "independent": "bağımsız", "other": "diğer", "radical": "radikal", "African": "Afrikalı", "young": "genç", "very": "çok", "because": "çünkü", "while": "iken", "often": "sık sık" },
        questions: [ {q:"Was Thomas Sankara the President of Burkina Faso?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live a simple life?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he plant millions of trees?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a strong supporter of women's rights?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to rely on money from other nations?", a_en:"No", a_tr:"Hayır"}, {q:"Was he killed in a coup?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he often called the African Che Guevara?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "21_YasserArafat.mp3": [{
        text: `Yasser Arafat was the most famous leader of the Palestinian people for many decades. He spent his whole life fighting for a country for his people. He was the founder of the Fatah movement and the leader of the PLO. He was a very complicated man who used both war and peace to achieve his goals. In 1993, he signed a peace agreement with Israel and won the Nobel Peace Prize. He became the first President of the Palestinian Authority. He was a symbol of his people’s struggle, always wearing his famous "kuffiyeh" scarf. Whether people agreed with him or not, everyone knew he was a man who never stopped fighting for Palestine until he died.`,
        dict: { "leader": "lider", "people": "insanlar", "decades": "on yıllar", "life": "hayat", "country": "ülke", "founder": "kurucu", "movement": "hareket", "man": "adam", "war": "savaş", "peace": "barış", "goals": "hedefler", "agreement": "anlaşma", "Prize": "ödül", "President": "başkan", "Authority": "yönetim", "symbol": "sembol", "struggle": "mücadele", "scarf": "eşarp/atkı", "everyone": "herkes", "Palestine": "Filistin", "spent": "geçirdi", "fighting": "savaşma", "used": "kullandı", "achieve": "ulaşmak", "signed": "imzaladı", "won": "kazandı", "became": "oldu", "wearing": "giyen/takan", "agreed": "katıldı", "knew": "biliyordu", "stopped": "durdurdu", "died": "öldü", "famous": "ünlü", "Palestinian": "Filistinli", "many": "birçok", "whole": "bütün", "complicated": "karmaşık", "both": "her ikisi", "Nobel": "Nobel", "first": "ilk", "most": "en", "very": "çok", "always": "her zaman", "Whether": "olsa da/olup olmadığı", "not": "değil", "never": "asla", "until": "kadar" },
        questions: [ {q:"Was Yasser Arafat a famous leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he spend his whole life fighting for his people?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the founder of the Fatah movement?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sign a peace agreement with Israel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Nobel Peace Prize?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he wear a famous scarf?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he ever stop fighting before he died?", a_en:"No", a_tr:"Hayır"} ]
    }]
};
